import os

SECRET_KEY = '361ea895-4bae-43a8-b0a5-c8c35bf6a920'
SIMPLELOGIN_BLUEPRINT = os.getenv('SIMPLELOGIN_BLUEPRINT')
SIMPLELOGIN_LOGIN_URL = os.getenv('SIMPLELOGIN_LOGIN_URL')
SIMPLELOGIN_LOGOUT_URL = os.getenv('SIMPLELOGIN_LOGOUT_URL')
SIMPLELOGIN_HOME_URL = os.getenv('SIMPLELOGIN_HOME_URL')
# ROOT_URLCONF = 'Calendar_Task_Login.Calendar_Task_Login.urls'
